fn main() -> Result<(), std::io::Error> {
    println!("Hello, world! This doesn't do much yet.");
    Ok(())
}